services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "./wait-for-it.sh postgresql 5432 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
    env_file:
      - ./.env

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-default_db}
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgresql