"""add

Revision ID: 720a7fd59182
Revises: 
Create Date: 2024-12-06 14:24:57.512547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720a7fd59182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id_pessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=35), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('celular', sa.CHAR(length=11), nullable=False),
    sa.Column('telefone', sa.CHAR(length=11), nullable=True),
    sa.Column('cpf', sa.CHAR(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('genero', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id_pessoa'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
