"""atualização de tabela

Revision ID: d592762b30f6
Revises: 8fd0a7b54aaf
Create Date: 2024-12-11 20:48:06.806917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd592762b30f6'
down_revision: Union[str, None] = '8fd0a7b54aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espaco_instituicao', sa.Column('disponibilidade', sa.String(length=35), nullable=False))
    op.add_column('eventos', sa.Column('qnt_voluntarios', sa.Integer(), nullable=False))
    op.add_column('instituicao_social', sa.Column('senha', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instituicao_social', 'senha')
    op.drop_column('eventos', 'qnt_voluntarios')
    op.drop_column('espaco_instituicao', 'disponibilidade')
    # ### end Alembic commands ###
